import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
     <div className="flex items-center justify-center">
        <div className="flex w-1/4">sidebar</div>
        <div className="flex w-3/4">{children}</div>
     </div>
      
      </body>
  </html>
  );
}
